### ISSUE TITLE
FSLDIR not found within ~/.bashrc error

### ISSUE THREAD

**Issue by AdebayoBraimah** [PichardRarker/fsleyes-for-windows#1]
Hi @PichardRarker , thanks for releasing this to the general public. I saw the post that was made sometime ago on the FSL message boards linking back to this git repository. 

I followed the installation instructions as posted in the README (aside from having `FSLDIR` set to the default path - as mine is set to `/usr/local/fsl/6.0.3`).

I compiled the C# sharp code using the developer command prompt from visual studio code 2017.

The `fsleyes.exe` file appears afterword - however, fails to launch with the error appearing in the log file: ```FSLDIR not found within ~/.bashrc.```

I was wondering if you had encountered this issue at some point?

Best,

--

Edit: grammar

**Comment by PichardRarker** [comment]
Hi @AdebayoBraimah 

Thanks for reporting this, and sorry for the delay in getting back to you. 

This stems from a Ubuntu quirk whereby ~/.bashrc prevents itself being evaluated if running in a non-interactive shell. I thought I'd gotten round this using the following environment variable hack on line 49 of `fsleyes_wrapper.sh`

`export PS1=123`

.. but clearly this solution isn't robust across recent Ubuntu distros. 

I've found a solution [here](https://askubuntu.com/questions/64387/cannot-successfully-source-bashrc-from-a-shell-script). Can you try changing line 1 of `fsleyes_wrapper.sh` from:

`#!/bin/bash`

to:

`#!/bin/bash -i`

... and then re-running `fsleyes.exe`? You shouldn't need to recompile the programme. 

If this works for you, I'll add this change to the repo. 

Best,

Rich

**Comment by AdebayoBraimah** [comment]
Hi @PichardRarker, that fix worked perfectly.
